using TFramework;
using UnityEngine;
using System;
using Object = UnityEngine.Object;
using System.Collections.Generic;


namespace TFramework
{
    public class DebugComponent : MonoBehaviour
    {
        [Serializable]
        public struct ComponentInfo
        {
            public string m_name;
            public BaseComponent m_prefab;
        }

        [SerializeField]
        ComponentInfo[] m_components;

        public ComponentInfo[] Components => m_components;

        private int _curIndex;

        public void Awake()
        {

        }

    }
}